#!/usr/bin/env bats
# Tests for .github/actions/discord-release-notify/action.yml.
#
# The shell logic lives inline in the single `run:` block of
# discord-release-notify/action.yml. The snippet below is a verbatim copy of
# that block so this test breaks if the action logic changes without updating
# the test (same convention as tests/bats/test_preflight.bats).
#
# The block carries no `set -e` of its own, so it is executed under
# `bash -eo pipefail`, which is the default shell GitHub uses for a composite
# `shell: bash` step.
#
# Covers:
#   - empty webhook_url is a no-op: exit 0, nothing posted
#   - repo -> mascot mapping for bluefin-lts, dakota and the catch-all default
#     (bot name, avatar URL and card slug)
#   - the release card is fetched from docs.projectbluefin.io for the mapped slug
#   - tag -> pretty date in the forum thread title, and the fallback to the raw
#     tag when the tag has no parseable YYYYMMDD suffix
#   - the posted payload_json carries username, avatar_url, thread_name and an
#     empty allowed_mentions parse list
#   - the card PNG is attached as files[0] and the webhook URL is the target
#   - a non-200 webhook response fails the step with the status in the message
#   - a failing card download fails the step before anything is posted

SNIPPET=$(cat <<'SNIP'
[ -n "$WEBHOOK_URL" ] || { echo "No Discord webhook URL configured, skipping."; exit 0; }

repo_short="${REPO##*/}"

card_file="/tmp/release-card-dark.png"

# Derive mascot avatar + display name from repo name
# Mapping mirrors generate-card-images.mjs in projectbluefin/documentation
DOCS_RAW="https://raw.githubusercontent.com/projectbluefin/documentation/main/static/img"
case "${REPO}" in
  */bluefin-lts) bot_name="Bluefin LTS"; avatar_url="${DOCS_RAW}/bluefin-lts-release-bot.svg"; card_slug="bluefin-lts" ;;
  */dakota)      bot_name="Dakota";       avatar_url="${DOCS_RAW}/characters/dakotaraptor.png"; card_slug="dakota" ;;
  *)             bot_name="Bluefin";      avatar_url="${DOCS_RAW}/bluefin-release-bot.png";     card_slug="bluefin" ;;
esac

# Pretty date from tag — stable-20260623 → "June 23, 2026"
date_raw="${TAG_NAME##*-}"
pretty_date=$(date -d "${date_raw:0:4}-${date_raw:4:2}-${date_raw:6:2}" "+%B %-d, %Y" 2>/dev/null || echo "$TAG_NAME")
post_title="${bot_name} — ${pretty_date}"

# Fetch the rich release card from the docs site — always reflects current release,
# includes kernel version, package counts, and raptor mascot artwork.
# Generated by projectbluefin/documentation scripts/generate-card-images.mjs
card_file="/tmp/release-card-dark.png"
curl -sfL "https://docs.projectbluefin.io/img/cards/${card_slug}-dark.png" -o "${card_file}"

# Post PNG as plain file attachment — Discord renders it full-width, no embed shrinkage
payload=$(jq -n \
  --arg thread_name "$post_title" \
  --arg bot_name "$bot_name" \
  --arg avatar_url "$avatar_url" \
  '{
    "username": $bot_name,
    "avatar_url": $avatar_url,
    "thread_name": $thread_name,
    "allowed_mentions": {"parse": []}
  }')

response=$(curl -sf -w "\n%{http_code}" \
  -H "User-Agent: DiscordBot (https://github.com/projectbluefin/common, 1.0)" \
  -F "payload_json=${payload}" \
  -F "files[0]=@${card_file};type=image/png" \
  "${WEBHOOK_URL}")

http_status=$(tail -1 <<< "$response")

[[ "$http_status" == "200" ]] || {
  echo "Discord post failed: HTTP $http_status" >&2
  exit 1
}
SNIP
)

setup() {
  TEST_TMP=$(mktemp -d)
  export TEST_TMP

  STUB_BIN="${TEST_TMP}/bin"
  mkdir -p "$STUB_BIN"
  export PATH="${STUB_BIN}:${PATH}"

  export WEBHOOK_URL="https://discord.example/api/webhooks/1/token"
  export TAG_NAME="stable-20260623"
  export REPO="projectbluefin/bluefin"

  echo "200" > "${TEST_TMP}/http_code"
  echo "0" > "${TEST_TMP}/card_rc"
  install_curl_stub
}

teardown() {
  rm -rf "$TEST_TMP"
}

# Records every invocation. A call carrying `-o` is the card download: it writes
# a placeholder file and honours ${TEST_TMP}/card_rc. Any other call is the
# webhook POST: it emits a body plus the status in ${TEST_TMP}/http_code, the
# same shape `curl -w "\n%{http_code}"` produces.
install_curl_stub() {
  cat > "${STUB_BIN}/curl" <<EOF
#!/usr/bin/env bash
printf '%s\n' "\$*" >> "${TEST_TMP}/curl_args"
for arg in "\$@"; do
  if [ "\$arg" = "-o" ]; then
    printf 'PNG' > "\${@: -1}"
    exit "\$(cat "${TEST_TMP}/card_rc")"
  fi
done
printf '%s\n' "\$*" > "${TEST_TMP}/post_args"
for arg in "\$@"; do
  case "\$arg" in
    payload_json=*) printf '%s' "\${arg#payload_json=}" > "${TEST_TMP}/payload_json" ;;
  esac
done
printf 'ok\n'
cat "${TEST_TMP}/http_code"
exit 0
EOF
  chmod +x "${STUB_BIN}/curl"
}

notify() {
  run bash -eo pipefail -c "$SNIPPET"
}

card_url() {
  head -1 "${TEST_TMP}/curl_args"
}

post_args() {
  cat "${TEST_TMP}/post_args"
}

payload_field() {
  jq -r "$1" < "${TEST_TMP}/payload_json"
}

# ── No-op path ────────────────────────────────────────────────────────────────

@test "empty webhook_url is a no-op and posts nothing" {
  export WEBHOOK_URL=""
  notify
  [ "$status" -eq 0 ]
  [[ "$output" == *"No Discord webhook URL configured, skipping."* ]]
  [ ! -f "${TEST_TMP}/curl_args" ]
}

# ── Repo → mascot mapping ─────────────────────────────────────────────────────

@test "bluefin-lts maps to the Bluefin LTS bot, avatar and card slug" {
  export REPO="projectbluefin/bluefin-lts"
  notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .username)" = "Bluefin LTS" ]
  [ "$(payload_field .avatar_url)" = "https://raw.githubusercontent.com/projectbluefin/documentation/main/static/img/bluefin-lts-release-bot.svg" ]
  [[ "$(card_url)" == *"/img/cards/bluefin-lts-dark.png"* ]]
}

@test "dakota maps to the Dakota bot, raptor avatar and card slug" {
  export REPO="projectbluefin/dakota"
  notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .username)" = "Dakota" ]
  [ "$(payload_field .avatar_url)" = "https://raw.githubusercontent.com/projectbluefin/documentation/main/static/img/characters/dakotaraptor.png" ]
  [[ "$(card_url)" == *"/img/cards/dakota-dark.png"* ]]
}

@test "an unmapped repo falls back to the Bluefin bot and card slug" {
  export REPO="projectbluefin/server"
  notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .username)" = "Bluefin" ]
  [ "$(payload_field .avatar_url)" = "https://raw.githubusercontent.com/projectbluefin/documentation/main/static/img/bluefin-release-bot.png" ]
  [[ "$(card_url)" == *"/img/cards/bluefin-dark.png"* ]]
}

@test "the card is fetched from the docs site with -sfL" {
  notify
  [ "$status" -eq 0 ]
  [[ "$(card_url)" == "-sfL https://docs.projectbluefin.io/img/cards/bluefin-dark.png -o /tmp/release-card-dark.png" ]]
}

# ── Tag → thread title ────────────────────────────────────────────────────────

@test "a dated tag becomes a pretty date in the thread name" {
  export TAG_NAME="stable-20260623"
  notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .thread_name)" = "Bluefin — June 23, 2026" ]
}

@test "the thread name uses the mapped bot name, not the repo name" {
  export REPO="projectbluefin/bluefin-lts"
  export TAG_NAME="stable-20260101"
  notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .thread_name)" = "Bluefin LTS — January 1, 2026" ]
}

@test "a tag with no parseable date falls back to the raw tag" {
  export TAG_NAME="not-a-date"
  notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .thread_name)" = "Bluefin — not-a-date" ]
}

# ── Payload and attachment shape ──────────────────────────────────────────────

@test "allowed_mentions suppresses every mention" {
  notify
  [ "$status" -eq 0 ]
  [ "$(payload_field '.allowed_mentions.parse | length')" = "0" ]
}

@test "the card PNG is attached as files[0] and posted to the webhook URL" {
  notify
  [ "$status" -eq 0 ]
  [[ "$(post_args)" == *"files[0]=@/tmp/release-card-dark.png;type=image/png"* ]]
  [[ "$(post_args)" == *"https://discord.example/api/webhooks/1/token"* ]]
}

@test "the post identifies itself with a DiscordBot user agent" {
  notify
  [ "$status" -eq 0 ]
  [[ "$(post_args)" == *"User-Agent: DiscordBot (https://github.com/projectbluefin/common, 1.0)"* ]]
}

# ── Failure paths ─────────────────────────────────────────────────────────────

@test "a non-200 webhook response fails the step and reports the status" {
  echo "429" > "${TEST_TMP}/http_code"
  notify
  [ "$status" -eq 1 ]
  [[ "$output" == *"Discord post failed: HTTP 429"* ]]
}

@test "a failing card download aborts before anything is posted" {
  echo "22" > "${TEST_TMP}/card_rc"
  notify
  [ "$status" -ne 0 ]
  [ ! -f "${TEST_TMP}/post_args" ]
}
