# This file is used to split existing images using `buildah build`. See
# README.md for how to use it.

ARG CHUNKAH=quay.io/coreos/chunkah:latest@sha256:8b56578258d1d10d3e1c7b0f71a4d05317c5fde331c4f483576a1b60e65f0cea
ARG CHUNKAH_ARGS=""
ARG CHUNKAH_CONFIG_STR

FROM overridden AS target
FROM ${CHUNKAH} AS chunkah
ARG CHUNKAH_CONFIG_STR
ARG CHUNKAH_ARGS
RUN --mount=type=bind,target=/run/src,rw \
    --mount=from=target,target=/chunkah,ro \
      chunkah build ${CHUNKAH_ARGS} --output oci:/run/src/out

FROM oci:out
