name: actionlint

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'bootc-build/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'bootc-build/**'

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run actionlint
        uses: reviewdog/action-actionlint@d63ba7532e0942965320cd8d73cbae4c7b3c5283 # v1.73.1
        with:
          reporter: github-pr-check
          fail_on_error: true
          # https://github.blog/changelog/2023-02-09-github-actions-update-on-code-and-workflow-permissions/
